### ISSUE TITLE
How to get the hash?

### ISSUE THREAD

**Issue by jershell** [WycliffeAssociates/jdenticon-kotlin#2]
i use as 
```
val svgString = Jdenticon.toSvg("simple string", 64, 0.2f)
```
i get this error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NumberFormatException: Invalid int: "o bar 2"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parse(Integer.java:375)
        at java.lang.Integer.parseInt(Integer.java:366)
        at jdenticon.IconGenerator.<init>(IconGenerator.kt:25)
        at jdenticon.Jdenticon$Companion.toSvg(jdenticon.kt:16)
```

**Comment by jsarabia** [comment]
Your input is a string, not a hash; you'd need to do something like:
```
val hash = String(Hex.encodeHex(DigestUtils.md5("simple string")))
val svgString = Jdenticon.toSvg(hash, 64, 0.2f)
```

Admittedly the library could be better if it was done from scratch; I had just quickly converted it to kotlin from the original javascript library.
